from __future__ import annotations

from pathlib import Path
import shutil

import pandas as pd


FIGURE_EXPLANATIONS = {
    "01_summary_dashboard.png": "Overall performance summary: distribution improvement, improved feature fraction, direction cosine and magnitude error.",
    "02_true_vs_virtual_heatmap.png": "Real KO delta, virtual KO delta and prediction error side by side.",
    "03_cell_state_umap.png": "Single-cell state movement: control, virtual KO and true KO cells.",
    "04_auc_strong_response_roc.png": "ROC curve for identifying strong KO-responsive features.",
    "05_prior_coverage.png": "Whether the requested KO genes are covered by pathway, TF, PPI or motif priors.",
    "07_uncertainty_intervals.png": "Hard-constrained residual uncertainty interval around predicted KO deltas.",
    "08_uncertainty_virtual_cell_pca.png": "Input, virtual KO and uncertainty virtual cells in state space.",
    "01_failure_diagnosis_overview.png": "KO-level reliability diagnosis: direction agreement and warning/high-risk feature counts.",
    "02_feature_error_heatmap.png": "Feature-level error heatmap showing where virtual KO differs from real KO.",
    "01_formal_benchmark_metric_panel.png": "Formal method benchmark panel comparing VKX against baselines and external methods when available.",
    "02_formal_benchmark_delta_heatmap.png": "True and predicted KO deltas across benchmarked methods.",
    "03_method_availability.png": "Which methods were actually run, provided externally, or not run in this benchmark.",
    "04_formal_benchmark_roc_curves.png": "Full ROC curves showing whether each method ranks strong KO-responsive features above weak-response features.",
    "01_hard_generator_metric_panel.png": "Evaluation of the hard-constrained residual generator while keeping the selected KO anchor direction fixed.",
    "02_hard_generator_intervals.png": "Feature-level uncertainty intervals sampled around the hard-constrained KO direction.",
    "03_hard_generator_true_virtual_heatmap.png": "True KO, virtual KO and error deltas side by side for the strongest state features.",
    "04_hard_generator_cell_state_pca.png": "Control, true KO and virtual KO cells in a low-dimensional state-space view.",
    "benchmark_overview.png": "Input benchmark readiness and perturbation label distribution.",
    "benchmark_modalities.png": "Detected RNA/protein/ATAC modality feature counts.",
    "double_interaction_metrics.png": "Single-gene additive vs interaction residual double-KO performance.",
    "peak_annotation.summary.png": "ATAC peak regulatory-prior QC: selected peaks and evidence components.",
}


def make_figure_package(result_dir: str | Path, out_dir: str | Path | None = None) -> pd.DataFrame:
    result = Path(result_dir)
    out = Path(out_dir) if out_dir else result / "figure_package"
    asset_dir = out / "assets"
    out.mkdir(parents=True, exist_ok=True)
    if asset_dir.exists():
        shutil.rmtree(asset_dir)
    asset_dir.mkdir(parents=True, exist_ok=True)
    rows = []
    for path in sorted(result.rglob("*.png")):
        if out in path.parents:
            continue
        dest_name = _unique_name(asset_dir, path.name)
        dest = asset_dir / dest_name
        shutil.copy2(path, dest)
        rows.append(
            {
                "figure": dest_name,
                "source": str(path),
                "explanation": FIGURE_EXPLANATIONS.get(path.name, _guess_explanation(path.name)),
            }
        )
    index = pd.DataFrame(rows)
    index.to_csv(out / "figure_index.csv", index=False)
    _write_report(index, out)
    return index


def _unique_name(asset_dir: Path, name: str) -> str:
    candidate = name
    stem = Path(name).stem
    suffix = Path(name).suffix
    i = 2
    while (asset_dir / candidate).exists():
        candidate = f"{stem}_{i}{suffix}"
        i += 1
    return candidate


def _guess_explanation(name: str) -> str:
    lower = name.lower()
    if "heatmap" in lower:
        return "Heatmap summarizing feature-level changes or errors."
    if "umap" in lower or "pca" in lower:
        return "State-space plot showing cell movement or group separation."
    if "auc" in lower or "roc" in lower:
        return "Curve-based discrimination metric for strong responses."
    if "confidence" in lower:
        return "Confidence or transferability diagnostic."
    if "peak" in lower:
        return "ATAC peak-level regulatory visualization."
    return "Result figure generated by the VKX workflow."


def _write_report(index: pd.DataFrame, out_dir: Path) -> None:
    lines = ["# VKX Figure Package", ""]
    if index.empty:
        lines.append("No PNG figures were found in the result directory.")
    else:
        lines.append("This package gathers the key generated figures and adds short explanations.")
        lines.append("")
        for _, row in index.iterrows():
            lines.append(f"## {row['figure']}")
            lines.append("")
            lines.append(f"![{row['figure']}](assets/{row['figure']})")
            lines.append("")
            lines.append(f"Explanation: {row['explanation']}")
            lines.append("")
            lines.append(f"Source: `{row['source']}`")
            lines.append("")
    (out_dir / "figure_package_report.md").write_text("\n".join(lines), encoding="utf-8")
